// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmohgkladwzzfsapwsrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtb2hna2xhZHd6emZzYXB3c3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTYyNjMsImV4cCI6MjA2OTUzMjI2M30.SwLP3U-F0H7gHV3p_MpbwGXOiXwfbm_hopx_uTp2sQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});